### ISSUE TITLE
Skylanders Emulated Portal is broken after Cemu 2.0-88 (Experimental) 

### ISSUE THREAD

**Issue by skylandersNFC** [cemu-project/Cemu#1284]
### Current Behavior

Skylanders Emulated Portal register all NFC dumps as broken toys after [Cemu 2.0-88 (Experimental)](https://github.com/cemu-project/Cemu/releases/tag/v2.0-88)

Example with [Cemu 2.0-91 (Experimental)](https://github.com/cemu-project/Cemu/releases/tag/v2.0-91)
![Cemu-91](https://github.com/user-attachments/assets/d6d1bc00-031a-4c7d-bd83-f6fa4f969250)

And working with [Cemu 2.0-88 (Experimental)](https://github.com/cemu-project/Cemu/releases/tag/v2.0-88)
![Cemu-88](https://github.com/user-attachments/assets/ceda491f-1e3d-4eb1-88d9-fe87e5d4e4ec)

### Expected Behavior

The emulated portal to work with the latest Cemu version as well.

### Steps to Reproduce

Use anything newer than [Cemu 2.0-88 (Experimental)](https://github.com/cemu-project/Cemu/releases/tag/v2.0-88) and you will see it.

Here is the dump i've used on the example above : https://github.com/skylandersNFC/Skylanders-Ultimate-NFC-Pack/raw/main/4.%20Trap%20Team/1)%20Trap%20Masters/Blastermind/Blastermind.dump

**Comment by Squall-Leonhart** [comment]
You mistake the cause with the fix,  that pr isn't present any cemu releases yet.

**Comment by Exzap** [comment]
I am pretty sure that #1275 is supposed to fix exactly this issue. There just hasn't been a new release since then.
There will be a new release later today. Please check if the issue still occurs and report back. You will to create new skylander files

**Comment by skylandersNFC** [comment]
@Exzap What do you mean by new skylanders files ?

I only use real NFC dumps for testing.
Don't trust emulators to create dumps, since in the past they were lacking SAK and ATAQ on Sector 0.
No idea what's the state nowadays and if this was fixed, but i think they still miss it.

**Comment by skylandersNFC** [comment]
The problem was fixed in [Cemu 2.0-92 (Experimental)](https://github.com/cemu-project/Cemu/releases/tag/v2.0-92)

**Comment by hYdos** [comment]
this problem was not fixed. I am crashing in Skylanders: Superchargers latest release as of 92

**Comment by Squall-Leonhart** [comment]
notice this issue wasn't about crashing

**Comment by skylandersNFC** [comment]
Here is the ticket about the crashing issues : https://github.com/cemu-project/Cemu/issues/1218
